### ISSUE TITLE
Add ability to select full quantity / total in order book market trading form

### ISSUE THREAD

**Issue by fubhy** [avantgardefinance/melon-terminal#302]
It would be nice to add the option to select a "max available balance" button that fills the form as follows: for sell orders, max is shown below quantity, and clicking on max will fill the quantity field with your total available balance of MLN tokens. For a buy order, the max button is shown below the total field, and fills with your total available balance of WETH.

**Comment by fubhy** [comment]
Follow up for #273

**Comment by iherger** [comment]
This has now been implemented.
