### ISSUE TITLE
Create custom decimal / bignumber aware input fields for token values

### ISSUE THREAD

**Issue by fubhy** [avantgardefinance/melon-terminal#303]
This input field could also have an icon prefix for the token that it represents.

Furthermore, we should ensure that the values we do any calculations with are ALWAYS represented in the full BigNumber format (no decimal places, full integer) and then only for the actual form representation we show it using decimals.

This should be a first step towards fixing the immense burden of juggling decimals around in all our forms.

**Comment by iherger** [comment]
This has been implemented recently.
