### ISSUE TITLE
Mainnet Create Fund Issue

### ISSUE THREAD

**Issue by rjoshig** [avantgardefinance/melon-terminal#371]
Wallet Used : Metamask/Ledger

**Low gas:** tx timed out in ui after about 15 mins. But etherscan shows tx not confirmed.  Why would ui shows timed out if tx is still pending? Is the UI timeout error polling eth blockchain?

```
Error message: 
Timeout exceeded during the transaction confirmation process. Be aware the transaction could still get confirmed!
Report error
```

**Issues:**
Misleading a bit. 
Resubmitted with average gas price which timed out
Resubmitted with fast , timed out again.

Tx still pending in block chain. 42 mins so far.

**Comment by fubhy** [comment]
With low gas the tx will need a lot of time to get executed. According to your description you now have 3 pending transactions. Instead of adding more on top you might want to cancel your tx and try again with a higher gas price to speed it up.
