### ISSUE TITLE
Add icon for connecting with Coinbase Wallet / Dapper

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#376]

**Comment by fubhy** [comment]
Dapper / Coinbase / MetaMask / etc. use the same `window.ethereum` global to inject their web3 connection providers. We need to make this explicit also in the dropdown menu. E.g. if the user has MetaMask injected, we should show MetaMask and grey out the other ones (Coinbase / Dapper / etc.) and vica versa.

**Comment by fubhy** [comment]
@ishak-lm I added the implementation but we don't have an icon for Coinbase and Dapper yet. Can you add one for this in the morning?

**Comment by fubhy** [comment]
@ishak-lm Actually, we just need an icon for Dapper. Coinbase will not be displayed on the browser normally, only when using the Coinbase app so we don't need an icon for that.

For Dapper, however, I could not find a SVG icon at all. So we might have to create one from their PNG icons (the little purple monster) or maybe even add a way to use PNGs in there. Can you work on that tomorrow? :-)
