### ISSUE TITLE
Inception date and performance fee period date are shown in different timezones 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#382]
<img width="539" alt="Capture d’écran 2020-02-20 à 13 19 38" src="https://user-images.githubusercontent.com/17808182/74933463-472cf900-53e4-11ea-8e0e-0731dd11234b.png">

**Comment by iherger** [comment]
I saw that as well and I assume it's connected to daylight savings time.

**Comment by jennazenk** [comment]
epic

**Comment by hjhettich** [comment]
Could you use a UTC timestamp? With this, checks with trx on e.g. Etherscan, Uniswap etc. would be much easier.

**Comment by fubhy** [comment]
Hm... I actually like that we show times using the user's local / browser time. Granted, Etherscan doesn't, but I'd argue that showing it in your own time is actually nicer. What we could think about is adding a hover box / tooltip (like for token values) where we show the UTC conversion of a time.

**Comment by jennazenk** [comment]
With UTC we could still show a user's local time

**Comment by fubhy** [comment]
Not sure what you mean. If we show the time in UTC, then e.g., if it's 4:30PM in UTC it would actually mean 5:30 PM GMT+1. 

So these are the same: 

4:30 PM UTC
5:30 PM GMT+1

I like the latter more because then I don't have to do the conversion in my head (to my own time).

**Comment by jennazenk** [comment]
you can show  local time UTC+1 for ex

**Comment by fubhy** [comment]
Right, so not plain UTC+0 but rather UTC relative to the local time zone. That's possible but that doesn't solve the problem that @hjhettich mentioned because Etherscan does UTC+0 (always show plain UTC regardless of local timezone).
