### ISSUE TITLE
Fund Contracts

### ISSUE THREAD

**Issue by hjhettich** [avantgardefinance/melon-terminal#386]
<img width="645" alt="Screenshot 2020-02-20 at 16 51 33" src="https://user-images.githubusercontent.com/37518232/74953053-730aa780-5401-11ea-8fb9-6698d167fc20.png">

looks like you sort them alphabetically, but "registry" breaks ranks...

**Comment by fubhy** [comment]
The first few are the deployed fund contracts (individually deployed for the fund). The registry and version are the globally deployed version and registry contract that are only referenced in the fund. I believe the alphabetical order is purely coincidental.

**Comment by iherger** [comment]
We have regrouped the fund contracts slightly different now.
