### ISSUE TITLE
UI: Portfolio holdings are cut off at the end

### ISSUE THREAD

**Issue by lulepu** [avantgardefinance/melon-terminal#390]
<img width="715" alt="Bildschirmfoto 2020-02-22 um 09 28 35" src="https://user-images.githubusercontent.com/61269239/75089144-313f4580-5556-11ea-95c4-32860e5db656.png">

Scrolling works perfect, but the list should go a little further.

**Comment by fubhy** [comment]
Thanks for the report. Which browser and operating system are you on if I may ask?

**Comment by lulepu** [comment]
Mac Catalina and Brave

**Comment by fubhy** [comment]
Thanks. Can you do me a favor and verify whether you also see this user interface glitch on Chrome or Firefox?

**Comment by lulepu** [comment]
yes sure. Its the same with firefox. i can see every token. its just, that there is a weird white space between the last token and the edge of the box.

**Comment by fubhy** [comment]
Should be fixed. Thanks for the report!
