### ISSUE TITLE
Can't shut down the fund

### ISSUE THREAD

**Issue by xhipster** [avantgardefinance/melon-terminal#391]
![Screenshot 2020-02-22 at 16 27 43](https://user-images.githubusercontent.com/410789/75094975-61a3d580-5590-11ea-98e6-ee4e010c1cb9.png)

Got this issue while trying to shutdown the fund

(Error in transaction "Return assets to vault")

**Comment by fubhy** [comment]
Thanks for the report. The source of the error has been identified. We'll push a fix early this week and update you here.

**Comment by fubhy** [comment]
@xhipster I just deployed a fix that should also cover your problem. Can you try again? Please make sure to hard-refresh your browser window in case you still have it open somewhere in a tab.

**Comment by xhipster** [comment]
Yep, thanks  :-) Now it works

**Comment by fubhy** [comment]
Great, thanks for reporting back!
