### ISSUE TITLE
Check accuracy of information shown in wallet page

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#392]
![IMAGE 2020-02-22 21:33:27](https://user-images.githubusercontent.com/17808182/75098808-f6bbc400-55ba-11ea-9d9b-054a43a9486c.jpg)

From Dima: I dont think that the information shown is correct as the fund currently has zero aum

**Comment by iherger** [comment]
The data displayed comes from the subgraph. Currently, some data in the subgraph is only updated with every price update, and it can be out of sync in-between price updates.

Working on a fix for the subgraph.

**Comment by iherger** [comment]
A fix for the melon subgraph has been deployed. 

I am closing this issue. Feel free to re-open this issue of create a new one if you observe other inconsistencies between data on the subgraph on on-chain data.
