### ISSUE TITLE
Average monthly return since fund inception 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#393]
From Dima: At this page I would love to see integral indicator of the avarage monthly profitability/loss of the fund since inception. Although it is easy to compute from date and share price fields This metirc is so important that I would make this sorter by default becuase this the most important metrics for potential investors
![IMAGE 2020-02-22 21:34:28](https://user-images.githubusercontent.com/17808182/75098822-1bb03700-55bb-11ea-94ae-35f7a54fecac.jpg)

**Comment by iherger** [comment]
I think we should implement this as part of a wider project to have more performance and risk measures (after the release).
