### ISSUE TITLE
Error in fund setup 

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#395]
From Mesnia: so i see this error while creating the vault contract..metamask was asking me to confirm at this point.. but modal shows an error...

![IMAGE 2020-02-22 21:36:13](https://user-images.githubusercontent.com/17808182/75098843-59ad5b00-55bb-11ea-8b5b-8480bc53b7d1.jpg)

**Comment by iherger** [comment]
Closing, since this seems to have been a one off issue.
