### ISSUE TITLE
Gas price

### ISSUE THREAD

**Issue by hjhettich** [avantgardefinance/melon-terminal#412]
<img width="630" alt="Screenshot 2020-02-24 at 17 17 16" src="https://user-images.githubusercontent.com/37518232/75170001-bd559680-5729-11ea-9f64-7379347bd16b.png">
It reads much nicer if you line break "Gas Price" to the second line in all three boxes.
First line -> Low / Average / Fast
Second line -> Gas Price
That is for all trx with the Melon Terminal.

**Comment by iherger** [comment]
This has been implemented.
