### ISSUE TITLE
Validation Error on Fund Creation with Fortmatic

### ISSUE THREAD

**Issue by erin-koen** [avantgardefinance/melon-terminal#416]
From Telegram testing group, user got "Validation Error: Undefined JSON-RPC result" on clicking "Create a Fund" after selecting exchanges and assets

**Comment by erin-koen** [comment]
![image](https://user-images.githubusercontent.com/46381469/75180058-6a6be700-5709-11ea-8301-2dbe6b882642.png)

**Comment by swandogg411** [comment]
Do these ever get addressed?

**Comment by iherger** [comment]
This should be fixed now.
