### ISSUE TITLE
"Could not find block" error when using WalletConnect

### ISSUE THREAD

**Issue by fubhy** [avantgardefinance/melon-terminal#435]
Hey @pedrouid, I just merged your PR to staging and was wondering if you had a clue what the "Could not find block" could be all about? We had the same problem last time we tried to integrate WalletConnect. We are querying block numbers a lot in our app, is there a problem with that somehow?

**Comment by fubhy** [comment]
Note: It seems like this error primarily occurs on localhost.

**Comment by pedrouid** [comment]
I think I've seen that error message before but I think it's not blocking any transactions, right?

**Comment by fubhy** [comment]
It breaks the dev environment because of how CRA works but yes, it's not blocking any transactions.

I am still struggling to make it "work" on the staging environment though. I've used `test.walletconnect.org` on Rinkeby and Kovan (send some test ETH to the addresses I got).

I tried to run a fund setup but couldn't get my transactions to pass. Any hints?

**Comment by pedrouid** [comment]
Let's try to use the web3-provider using the next tag instead of latest

```
yarn add @walletconnect/web3-provider@next
```

I haven't released these changes to latest because of other packages on the monorepo but maybe this version will fix it

**Comment by fubhy** [comment]
Alright, will give that a shot!

**Comment by fubhy** [comment]
Alright, so the problem is that eth.getBlockNumber() never resolves the promise. Does your provider somehow prevent fetching block numbers or blocks / filters these requests elsewhere?

**Comment by pedrouid** [comment]
Thanks for looking into it 🙏 I will try to get a fix in soon

**Comment by pedrouid** [comment]
Hey @fubhy, could you try this integration now with the beta.100?

**Comment by pedrouid** [comment]
a few iterations more now on the 1.0.0-rc.0... let me know how it goes

**Comment by pedrouid** [comment]
You should be able to have a stable integration with latest release 💪

**Comment by fubhy** [comment]
Thanks! I re-added it to our app now and it seems to work fine. Will include it in our next deployment. Will let you know if something doesn't work yet!
