### ISSUE TITLE
Management Fee discrepancy 

### ISSUE THREAD

**Issue by slimjk** [avantgardefinance/melon-terminal#442]
Selected 1.5% as my MF during the fund setup process, after completion, the fund fact sheet is showing 2%.  However, at Gorilla Funds site it is showing the 1.5%

**Comment by iherger** [comment]
Thanks for reporting. This has now been fixed and you should be able to see it on https://melon.avantgarde.finance/ (you may need to reload the app to see it).

**Comment by slimjk** [comment]
Yep, fixed thank you.
