### ISSUE TITLE
Feedback: Fund creation in one transaction for better UX

### ISSUE THREAD

**Issue by carumusan** [avantgardefinance/melon-terminal#451]
It took around 1 hour to create a fund with a lot of waiting for transactions to confirm because of the volatility of network congestion. I think grouping into as few transactions as possible would greatly improve the onboarding experience. Maybe even have a contract where you deposit the funds needed to start the fund and the contract takes care of the rest.

**Comment by fubhy** [comment]
Hey there. Indeed! We are aware of this and there is actually an open issue for that on the protocol repository: https://github.com/melonproject/protocol/issues/813

You can follow that one for future updates!
