### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by plutoegg** [avantgardefinance/melon-terminal#456]
Parameter|Value
------|-----
Contract|[0x1205c8acC24b29d0884f15D3417F7d63FEc92D96](https://etherscan.io/address/0x1205c8acC24b29d0884f15D3417F7d63FEc92D96)
Method|executeRequestFor
Arguments|["0x05e3fddf871bcba3f0651fb01fd0d621ad087be2"]
Sender|[0x05e3fddf871bcba3f0651fb01fd0d621ad087be2](https://etherscan.io/address/0x05e3fddf871bcba3f0651fb01fd0d621ad087be2)

**Comment by iherger** [comment]
This seems to have been caused the an invalid MKR price at the time of the attempted transaction.
