### ISSUE TITLE
Error in transaction "Redeem shares"

### ISSUE THREAD

**Issue by Beaudelair** [avantgardefinance/melon-terminal#458]
Parameter|Value
------|-----
Contract|[0x72c20a44135DB27249f7F24262cd2815c45719e7](https://etherscan.io/address/0x72c20a44135DB27249f7F24262cd2815c45719e7)
Method|redeemQuantity
Arguments|["1000000000000000000"]
Sender|[0xfd89d3831c6973fb5ba0b82022142b54ad9e8d46](https://etherscan.io/address/0xfd89d3831c6973fb5ba0b82022142b54ad9e8d46)

**Comment by Beaudelair** [comment]
I can't redeem my shares. Fund: Ad Astra

**Comment by iherger** [comment]
What's the error message that you are getting?

**Comment by Beaudelair** [comment]
gas required exceeds allowance (9986413) or always failing transaction

**Comment by jennazenk** [comment]
hey @Beaudelair we might need your help to debug this one as we can't reproduce it. Do you have a telegram handle at which we can reach you?

**Comment by Beaudelair** [comment]
Thank for taking time to look at it. I do, please PM me for telegram

**Comment by jennazenk** [comment]
can you send it to me at jenna@avantgarde.finance ?
