### ISSUE TITLE
Error in transaction "Take order on Kyber"

### ISSUE THREAD

**Issue by Adrianjg** [avantgardefinance/melon-terminal#459]
Parameter|Value
------|-----
Contract|[0x7c31eC6856a921ADbe18abCDf19F0113EDDcC1e9](https://etherscan.io/address/0x7c31eC6856a921ADbe18abCDf19F0113EDDcC1e9)
Method|callOnExchange
Arguments|["1","takeOrder(address,address[8],uint256[8],bytes[4],bytes32,bytes)",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],["19389946577720577","50000000000000000","0","0","0","0","50000000000000000","0"],["0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000"],"0x0000000000000000000000000000000000000000000000000000000000000000",[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
Sender|[0x68B24f2d29907B0B836A2526A46269Cd8869050a](https://etherscan.io/address/0x68B24f2d29907B0B836A2526A46269Cd8869050a)

Stack trace: Error: Node error: {"code":-32000,"message":"gas required exceeds allowance (9849795) or always failing transaction"}
    at Function.value (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:726356)
    at e.<anonymous> (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:738026)
    at c (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198448)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198201)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198805)
    at r (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070022)
    at s (https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070233)

![Buying MKR](https://user-images.githubusercontent.com/25788278/76152585-1fe65500-608f-11ea-8318-adb9b7bb6fc7.png)
![Error MKR](https://user-images.githubusercontent.com/25788278/76152581-19f07400-608f-11ea-823e-6aee5f2753ea.png)
![Buying LINK](https://user-images.githubusercontent.com/25788278/76152588-2ecd0780-608f-11ea-9cf1-8fb8880d1323.png)
![Error LINK](https://user-images.githubusercontent.com/25788278/76152590-355b7f00-608f-11ea-8cc9-ec0560cbbb21.png)

**Comment by Adrianjg** [comment]
Hello, every time I tried to buy an asset from my fund I got that error message. I used to get the same message in the previous version of Melon.

I have sufficient WETH in my fund and ETH in my manager wallet to do a transaction

**Comment by jennazenk** [comment]
Hey Adrian, can you give us the fund name or address?

**Comment by Adrianjg** [comment]
Hey Jenna, the fund's name is TJ Capital Inc

**Comment by iherger** [comment]
This was a bug in `melonjs`, where the incorrect PriceTolerance contract was deployed, and consequently, all PriceTolerance policy checks failed when attempting any trade. 

It has been fixed in `melonjs` and the Melon Terminal is now deploying the correct PriceTolerance policy contract.
