### ISSUE TITLE
Error in transaction "Approve"

### ISSUE THREAD

**Issue by jeanmatthieu58** [avantgardefinance/melon-terminal#461]
hi, I have another problem "Undefined JSON-RPC"
Parameter|Value
------|-----
Contract|[0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2](https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2)
Method|approve
Arguments|["0x9fedE1B116Ae1b2a58113Edb4E0C2886381798B3","1000000000000000000"]
Sender|[0x4CF1FC305Dfb17E01fD47A16e65BdC980F7e451D](https://etherscan.io/address/0x4CF1FC305Dfb17E01fD47A16e65BdC980F7e451D)

Stack trace: value@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:726574
https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:747617
c@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198452
https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:7198202
r@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070022
s@https://melon.avantgarde.finance/static/js/6.e98349f5.chunk.js:2:1070234
promiseReactionJob@[native code]

**Comment by iherger** [comment]
This is likely also fixed with the Fortmatic update. If not, please feel free to reopen the issue.
