### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by jeanmatthieu58** [avantgardefinance/melon-terminal#462]
Parameter|Value

Hi ivan 
i made another and the problem still there 
------|-----
Contract|[0x9fedE1B116Ae1b2a58113Edb4E0C2886381798B3](https://etherscan.io/address/0x9fedE1B116Ae1b2a58113Edb4E0C2886381798B3)
Method|requestInvestment
Arguments|["1000000000000000000","1000000000000000000","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"]
Sender|[0x4CF1FC305Dfb17E01fD47A16e65BdC980F7e451D](https://etherscan.io/address/0x4CF1FC305Dfb17E01fD47A16e65BdC980F7e451D)

Stack trace: value@https://melon.avantgarde.finance/static/js/6.69c8ff5c.chunk.js:2:726365
https://melon.avantgarde.finance/static/js/6.69c8ff5c.chunk.js:2:747617
c@https://melon.avantgarde.finance/static/js/6.69c8ff5c.chunk.js:2:7198452
https://melon.avantgarde.finance/static/js/6.69c8ff5c.chunk.js:2:7198202
r@https://melon.avantgarde.finance/static/js/6.69c8ff5c.chunk.js:2:1070022
s@https://melon.avantgarde.finance/static/js/6.69c8ff5c.chunk.js:2:1070234
promiseReactionJob@[native code]

**Comment by iherger** [comment]
Thanks for reporting.

Could you please try your transaction on the following deployment (which has been made especially for debugging the invest transaction): https://melon-terminal-git-debug-invest-transaction.avantgarde-finance.now.sh

**Comment by jeanmatthieu58** [comment]
I did it in first but there wasn’t any bug

**Comment by jeanmatthieu58** [comment]
Are you on telegram?

**Comment by iherger** [comment]
Yes, I am on Telegram. I just sent you a message there.

**Comment by iherger** [comment]
This was due to a bug in Fortmatic, which has now been fixed on their side.
