### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by rudalmia** [avantgardefinance/melon-terminal#464]
Parameter|Value
------|-----
Contract|[0xD84e51ae9eb62fA8FccAfa98BE84f9d98b3d6Af6](https://etherscan.io/address/0xD84e51ae9eb62fA8FccAfa98BE84f9d98b3d6Af6)
Method|requestInvestment
Arguments|["170000000000000000","170000000000000000","0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"]
Sender|[0xF28B3c734a30aF72085208282226cD4D1196DEDE](https://etherscan.io/address/0xF28B3c734a30aF72085208282226cD4D1196DEDE)

Stack trace: value@https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:726365
https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:747617
c@https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:7198452
https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:7198202
r@https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:1070022
s@https://melon.avantgarde.finance/static/js/6.84c512e4.chunk.js:2:1070234
promiseReactionJob@[native code]

**Comment by iherger** [comment]
Thanks for reporting this. 

Did you get a more detailed error?

**Comment by rudalmia** [comment]
Node error: {"message":"\"gas\" is missing"}

**Comment by iherger** [comment]
That is strange, indeed.

If you are on Telegram, could you send your Telegram handle to ivan@avantgarde.finance, so we can debug there?

**Comment by iherger** [comment]
Closing this, seems to have been a one-off error.
