### ISSUE TITLE
Error in transaction "Take order"

### ISSUE THREAD

**Issue by erin-koen** [avantgardefinance/melon-terminal#470]
Error message: gas required exceeds allowance (9990236) or always failing transaction
Fund: EEK Capital
URL: https://melon.avantgarde.finance/mainnet/fund/0x69591BFb5667d2d938ad00EF5da8aDDBCf811bc9/trade
Contract: [0xf88Ea509c836CbC29e15A55ea9C1fb7251002a92](https://etherscan.io/address/0xf88Ea509c836CbC29e15A55ea9C1fb7251002a92)
Method: callOnExchange
Arguments: ["2","takeOrder(address,address[8],uint256[8],bytes[4],bytes32,bytes)",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2","0x6b175474e89094c44da98b954eedeac495271d0f","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],["72585866364081244","20000000000000000000","0","0","0","0","20000000000000000000","0"],["0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000"],"0x0000000000000000000000000000000000000000000000000000000000000000",[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
Sender: [0xe5fd31e9028f156396cf0b37833fc449fd3bfe57](https://etherscan.io/address/0xe5fd31e9028f156396cf0b37833fc449fd3bfe57)
Connection: metamask
Network: MAINNET

**Comment by iherger** [comment]
This was fixed recently (there was a mixup of exchange adapters in melonjs, which has been resolved).
