### ISSUE TITLE
Error in transaction "Create Vault Contract"

### ISSUE THREAD

**Issue by raphalice** [avantgardefinance/melon-terminal#498]
Error message: Transaction has been reverted by the EVM:
{
  "blockHash": "0x94fd8c8a9a40b7c034371e5ede196297d4652e4bb167fd91156221ea150d41fd",
  "blockNumber": 9826136,
  "contractAddress": null,
  "cumulativeGasUsed": 4802182,
  "from": "0xa73557c2749fea5a185eae5facf9ef310c76ea6a",
  "gasUsed": 23915,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x5f9ae054c7f0489888b1ea46824b4b9618f8a711",
  "transactionHash": "0x598400617f115edeadd3b30e1117ebe9c5012ad7a637e8902006e77b2419d222",
  "transactionIndex": 78
}
Fund: Blazar 1
URL: https://melon.avantgarde.finance/mainnet/fund/0x995d1330cB59b66aDE4B39b07fc1c4F1aBaa44C0
Contract: [0x5f9AE054C7F0489888B1ea46824b4B9618f8A711](https://etherscan.io/address/0x5f9AE054C7F0489888B1ea46824b4B9618f8A711)
Method: createVaultFor
Arguments: ["0xa73557c2749fea5a185eae5facf9ef310c76ea6a"]
Sender: [0xa73557c2749fea5a185eae5facf9ef310c76ea6a](https://etherscan.io/address/0xa73557c2749fea5a185eae5facf9ef310c76ea6a)
TxHash: [0x598400617f115edeadd3b30e1117ebe9c5012ad7a637e8902006e77b2419d222](https://etherscan.io/tx/0x598400617f115edeadd3b30e1117ebe9c5012ad7a637e8902006e77b2419d222)
Connection: metamask
Network: MAINNET
Stack trace: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x94fd8c8a9a40b7c034371e5ede196297d4652e4bb167fd91156221ea150d41fd",
  "blockNumber": 9826136,
  "contractAddress": null,
  "cumulativeGasUsed": 4802182,
  "from": "0xa73557c2749fea5a185eae5facf9ef310c76ea6a",
  "gasUsed": 23915,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x5f9ae054c7f0489888b1ea46824b4b9618f8a711",
  "transactionHash": "0x598400617f115edeadd3b30e1117ebe9c5012ad7a637e8902006e77b2419d222",
  "transactionIndex": 78
}
    at t._next (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:1019727)
    at t.__tryOrUnsub (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:144939)
    at t.next (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:144084)
    at t._next (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:143160)
    at t.next (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:142831)
    at e.value (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:1010521)
    at https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:1008684
    at c (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:7089950)
    at Generator._invoke (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:7089703)
    at Generator.forEach.e.<computed> [as next] (https://melon.avantgarde.finance/static/js/6.a7121eb8.chunk.js:2:7090307)

**Comment by iherger** [comment]
Thanks for reporting this, @raphalice .

First of all, your find now seems to have been setup, which is good!

For the error you are reporting, it seems that you tried to create the vault contract a second time, i.e. you tried to send the same transaction twice. Can you give us some background as to how this happened?

**Comment by raphalice** [comment]
Sure Ivan. I also got an error message the first time and a prompt to
redeploy the contract. I didn't think of recording the logs at that point
and clicked the button. In all, throughout the set-up process, I got the
following failed transactions (
https://etherscan.io/address/0x5f9ae054c7f0489888b1ea46824b4b9618f8a711). I
don't know if they correspond to the logs I sent you:

[image: image.png]

Raphaël Mazet
CEO | Alice | @raph_alice
Please excuse any typos - sent from my mobile.
