### ISSUE TITLE
Error in transaction "Take order"

### ISSUE THREAD

**Issue by lulepu** [avantgardefinance/melon-terminal#500]
Error message: gas required exceeds allowance (9989994) or always failing transaction
Fund: Carneval
URL: https://melon.avantgarde.finance/mainnet/fund/0x2d1b95c9f9d1ea04bb91b0389ca62b0425257197/trade
Contract: [0x0A5d365B7d869a6534fb2438a12256f9C8a4db87](https://etherscan.io/address/0x0A5d365B7d869a6534fb2438a12256f9C8a4db87)
Method: callOnExchange
Arguments: ["2","takeOrder(address,address[8],uint256[8],bytes[4],bytes32,bytes)",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x408e41876cccdc0f92210600ef50372656052a38","0x514910771af9ca656af840dff83e8264ecf986ca","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],["4689958212316596468877","74000000000000000000","0","0","0","0","74000000000000000000","0"],["0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000000000000000000000000000"],"0x0000000000000000000000000000000000000000000000000000000000000000",[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]
Sender: [0xfd4e7749ef6310980831ee271cca0ee5c4302c98](https://etherscan.io/address/0xfd4e7749ef6310980831ee271cca0ee5c4302c98)
Connection: metamask
Network: MAINNET

**Comment by iherger** [comment]
I think this is the same issue as #527, so closing this as well.
