### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by nseidm1** [avantgardefinance/melon-terminal#532]
![image](https://user-images.githubusercontent.com/2364326/82853100-b712ba00-9ed2-11ea-8938-8b61cd979d8e.png)

**Comment by nseidm1** [comment]
No capacity to cancel the investment request or modify it.

![image](https://user-images.githubusercontent.com/2364326/82853610-32c13680-9ed4-11ea-9fdf-dd0abdf8bd4b.png)

**Comment by iherger** [comment]
Thanks for reporting this.

It seems that we re-introduced a rounding bug with the latest form-revamp which was deployed last week. We have just deployed a fix for this. Apologies for the inconvenience.

For background: your request for an investment of 54.6687 MLN was calculated to be 1.110835898049295130 shares, using the current MLN/WETH price (and the initial share price of 1). We should have rounded down that value to 1.110835898049295129 (last digit is different). With the incorrectly calculated number of shares, your investment amount is too low, and the transaction cannot be executed.

Your investment request might still be executable after the next price update (if the MLN price increases), and it will then be automatically executed. 

As you noticed, you cannot modify your investment request. You can cancel it after 24 hours, though, if it is not executed before.

**Comment by nseidm1** [comment]
No worries, <3

**Comment by nseidm1** [comment]
Albeit 1 further question.

https://etherscan.io/tx/0x639b833a92ae70b83a1d9da1d78de3968bb646eef7660351b67cda564e337d0e

54.67 melon appears to be in the participation contract.
