### ISSUE TITLE
Create a fund (melon terminal)

### ISSUE THREAD

**Issue by cocoper89** [avantgardefinance/melon-terminal#545]
![Uploading 84773196...]()

**Comment by iherger** [comment]
Thanks for getting in contact. I assume you wanted to post a screenshot, but that didn't come through. Can you try again?

**Comment by cocoper89** [comment]
I got charge .08 eth



[cid:726E906A-1087-4CF3-B04C-8DF17FA32285-L0-001]



Sent from my iPhone

On Jun 16, 2020, at 3:36 PM, Ivan Herger <notifications@github.com> wrote:

﻿

Thanks for getting in contact. I assume you wanted to post a screenshot, but that didn't come through. Can you try again?

**Comment by iherger** [comment]
I don't understand what the problem is. Can you give us more details?

**Comment by cocoper89** [comment]
Aparently the issue is solved

Sent from my iPhone

On Jun 16, 2020, at 3:46 PM, Ivan Herger <notifications@github.com> wrote:

﻿

I don't understand what the problem is. Can you give us more details?

**Comment by iherger** [comment]
OK, thank you for the update.
