### ISSUE TITLE
Error in transaction "Take order"

### ISSUE THREAD

**Issue by pete-roy** [avantgardefinance/melon-terminal#552]
I can't seem to be able to sell WETH for USDC, MLN, WBTC in the trading module.
I am using metamask, who is telling me the transaction failed due to ETH=0

**Comment by iherger** [comment]
This could be the problem that you don't have enough ETH in your wallet to pay for gas for that transaction. Can you check this?

**Comment by pete-roy** [comment]
Hi, I think the wallet is funded enough
The metamask comment in the error is 'transaction underpriced'

**Comment by pete-roy** [comment]
using very low gwei

**Comment by pete-roy** [comment]
but that should be slow, now fail, right?

**Comment by pete-roy** [comment]
do I need to first whitelist the assets I want to buy, in the ruleset?

**Comment by pete-roy** [comment]
all assets are now whitelisted, and the 'transaction underpriced' problem persists in metamask - thanks for what you can do

**Comment by pete-roy** [comment]
notification: transaction failed. Error  ; [ethjs-rpc] rpc error with payload
{"id": 5223559291871, "jsonrpc" :"2.0", "params": etc
