### ISSUE TITLE
Block trading feature

### ISSUE THREAD

**Issue by x829901** [avantgardefinance/melon-terminal#561]
Is there a way, or will there be a way, to block trade in the Melon terminal. That way I can execute multiple orders at once. Or set a portfolio allocation by some target percentage weighting. Thanks.

**Comment by iherger** [comment]
Improving trading is an important point for us, and we are currently actively looking into ways to have execute multiple orders or to route orders through smart order routers. No ETA at the moment, but it's definitely coming.

**Comment by x829901** [comment]
Thanks.
