### ISSUE TITLE
Error in transaction "Remove assets"

### ISSUE THREAD

**Issue by swandogg411** [avantgardefinance/melon-terminal#564]
Validation error undefined JSon-Rpc result
Numerous instances of this error preventing changes in admin parameters of the fund, etc

This error also pops up on the interface during trade requests etc with inconsistent results whether they go thru.

**Comment by iherger** [comment]
Thanks for reporting this.

Can you tell us which wallet your are using (i.e. Metamask, Frame, Fortmatic, etc)

**Comment by swandogg411** [comment]
Hi Ivan,
I am using Fortmatic currently

Thanks

Sent from my iPhone

On Jul 3, 2020, at 11:00 AM, Ivan Herger <notifications@github.com> wrote:

﻿

Thanks for reporting this.

Can you tell us which wallet your are using (i.e. Metamask, Frame, Fortmatic, etc)

**Comment by swandogg411** [comment]
Nothing seems to change or update in terminal after these transactions.ThanksSent from my iPhoneOn Jul 3, 2020, at 1:53 PM, E S <swandogg411@hotmail.com> wrote:﻿




Hi Ivan,
I am using Fortmatic currently


Thanks

Sent from my iPhone

On Jul 3, 2020, at 11:00 AM, Ivan Herger <notifications@github.com> wrote:




﻿

Thanks for reporting this.
Can you tell us which wallet your are using (i.e. Metamask, Frame, Fortmatic, etc)
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by iherger** [comment]
We pushed some changes to our Fortmatic integration, and this should now be fixed.
