### ISSUE TITLE
Error in transaction "Begin setup"

### ISSUE THREAD

**Issue by etiennebr71** [avantgardefinance/melon-terminal#565]
Hi - I keep getting "Component has already been set." when actually the fund has not been setup. Has anyone got this error? Thank you

**Comment by iherger** [comment]
Which wallet are you using?

**Comment by etiennebr71** [comment]
All good I was able to solve.
There was a syncing problem with metamask  





On Mon, Jul 6, 2020 11:56 AM, Ivan Herger notifications@github.com  wrote:


Which wallet are you using?
