### ISSUE TITLE
Error in transaction "Create Accounting Contract"

### ISSUE THREAD

**Issue by tullioetpompeo** [avantgardefinance/melon-terminal#566]
As I try to complete the fund setup process, after "Begin setup" I receive the following message:
Fortmatic RPC Error: [-32603] gas required exceeds allowance (11529821) or always failing transaction
I cannot move forward. What should I do?
Thank you for your help!

**Comment by iherger** [comment]
Thanks for reporting.

Using Fortmatic seems to be problematic, and we are looking into it. We would greatly appreciate your help in debugging the problem. If you would to help us, please send your email/telegram to ivan at avantgarde.finance

**Comment by iherger** [comment]
Can you check how much ETH you have in your wallet?

**Comment by tullioetpompeo** [comment]
I have a balance of 0.0453 ETH


Il giorno lun 6 lug 2020 alle ore 16:53 Ivan Herger <
notifications@github.com> ha scritto:

**Comment by iherger** [comment]
That balance of 0.0453 ETH in your wallet is probably too low. With current gas prices, you will probably need around 1 ETH in  your wallet to complete the whole fund setup process.
