### ISSUE TITLE
No price feed for Aragon Network Token on Melon Terminal 

### ISSUE THREAD

**Issue by rbgb1** [avantgardefinance/melon-terminal#567]
Please help with getting the Price feed from Kyber for $ANT, since the price feed is N/A the share quotes have no tolerance and the performance period is not tracking. example below
Share price

N/A

Assets under management

N/A

Daily change

0.00%

**Comment by rbgb1** [comment]
This should be resolved shortly. Some reserves on kyber have not upgraded to katalyst yet. Melon Protocol.

**Comment by iherger** [comment]
Thanks for reporting this. We are aware of the problem and we are working with Kyber and Aragon to have it solved asap.

**Comment by rbgb1** [comment]
Thank you for the communication.

**Comment by fubhy** [comment]
The price for ANT is back!
