### ISSUE TITLE
Unable to Trade or Invest

### ISSUE THREAD

**Issue by x829901** [avantgardefinance/melon-terminal#570]
I have tried to trade several times, several different coins, as well as invest more into my fund, both yesterday and today. All trades and attempts to invest have failed with the error report, "The price may have moved before the order was confirmed. Please try again." and when trying to invest in my fund, "The transaction has failed. This is an error."

![image](https://user-images.githubusercontent.com/57601600/86941245-58637180-c109-11ea-89a4-d478bfdb3475.png)

![image](https://user-images.githubusercontent.com/57601600/86944135-ee4ccb80-c10c-11ea-9c0b-880a5e496d37.png)

As such, my fund is dead in the water, completely unable to trade. It all started when ANT failed to get a quote from the Kyber Network yesterday and showed N/A for price resulting in all ANT-holding fund's AUM also showing N/A. ANT is now showing quotes as normal, AUM looks normal, but I still can't trade.

Etherscan is showing 3 pending transactions which have been pending for over 12 hours (highly unusual).  

![image](https://user-images.githubusercontent.com/57601600/86941625-c445da00-c109-11ea-85d2-f4d28b059e6d.png)

My Melon ETH wallet has a little over 1 ETH to pay gas fees so it can't be that.

**Comment by x829901** [comment]
Update: The pending trades executed. Took well over 12 hours. Weird.

**Comment by iherger** [comment]
Thanks for reporting this.

Can you tell us which wallet you are using?

**Comment by x829901** [comment]
Metamask
