### ISSUE TITLE
No current holdings 

### ISSUE THREAD

**Issue by nameulem** [avantgardefinance/melon-terminal#574]
Hi! 

There seems to be an issue with the potfolio holdings when connected.
I can see my fund's holdings when I'm not connected though..

Due to this issue, I can't make any trade with my fund at the moment.. 
I have tried with mozilla firefox and google chrome.

Please take a look at this.
Thanks.

**Comment by iherger** [comment]
Thanks for reporting this.

Can you tell us which fund this is, and what wallet you are using?

**Comment by nameulem** [comment]
Midas Invest : https://melon.avantgarde.finance/mainnet/fund/0x823871d20fabe1e2f5a40c5d9320f1cd01ca8841
Fortmatic Wallet

**Comment by iherger** [comment]
I can reproduce this error, which is really a Fortmatic error (it works well with all other wallets...):

```
Failed to call convertQuantity at 0x7fe3fe4b523d7f83dc05224573b01296877dc163: Error: Fortmatic RPC Error: [-32603] execution reverted: Price is not valid, Path: fund.routes.accounting.holdings
```

We will try to find what the reason for this Fortmatic error.

**Comment by fubhy** [comment]
This should be fixed. Can you give it another try? Thanks!
