### ISSUE TITLE
Error in transaction "Invest"

### ISSUE THREAD

**Issue by LinuxIsCool** [avantgardefinance/melon-terminal#577]
![image](https://user-images.githubusercontent.com/31582215/87486373-0aaaa580-c5f0-11ea-981a-932cb4780cf3.png)

**Comment by LinuxIsCool** [comment]
https://melon.avantgarde.finance/rinkeby/fund/0x81538e66f860Bf1409C061E89bAd20b58B6c168a/invest

**Comment by iherger** [comment]
That is a strange error... in principle, the Terminal is sending `approve` for the exact same amount that the investment request is. We will look into this.

For the time being, you can simply dismiss the warning, and click on the Invest button again, then the `requestInvestment` transaction will be started with the error.
