### ISSUE TITLE
Money Invested wont show up

### ISSUE THREAD

**Issue by nickbaes** [avantgardefinance/melon-terminal#579]
I have been waiting forever for the 1.5 weth to be added to the fund to invest.

You have a pending investment request:

Requested shares: 1.3189 Shares
Investment amount: 1.5000 WETH
Request date: 2020/07/17 06:26 GMT-4

Your investment request will be automatically executed after the next price update, which will be at approximately 2020/07/18 04:23 GMT-4.

If you come back during the execution window (which starts at around 2020/07/18 04:23 GMT-4 and ends at 2020/07/18 06:26 GMT-4), and your invesment request hasn't been automatically executed, you will see here the option to execute it yourself.

**Comment by fubhy** [comment]
Hey @nickbaes. You posted this message on July 17th and the message clearly states that the request will be executed on July 18th 4:23 GMT-4. I assume it has been executed now?

**Comment by Category55** [comment]
Hi 

I am trying to invest in a fund.

I sent $50 weth to the fund and sucessful. Then there was 2nd step which requested more fees this step was not successful. Please help with just geting my Ether back this melon protocol is clearly for genuis only
