### ISSUE TITLE
Invest transaction doesn't show in balance

### ISSUE THREAD

**Issue by bernardorq** [avantgardefinance/melon-terminal#580]
I tried investing in my recently created fund and no balance shows up after this transaction:

0x1b9288f388447ff817af9bdbc3f2ee482f2e8b92f793e2d3716346d8eed26b29

Any help?

Thanks,
Bernardo

**Comment by fubhy** [comment]
This is a wrap ether (ETH => WETH) transaction. That means you no own 2.7 WETH instead of ETH which you can invest into your fund. Once you've invested it in your fund it will show up as WETH in your fund holdings.
