### ISSUE TITLE
Error deploying Investor Whitelist Policy

### ISSUE THREAD

**Issue by Cryptojuju** [avantgardefinance/melon-terminal#584]
Despite 2 attempts (and 2 successful transactions) the Investor Whitelist Policy wasn't deployed successfully

**Comment by iherger** [comment]
We are investigating this.

**Comment by iherger** [comment]
Deploying policies is currently not possible when you are using an Argent wallet.

There is a workaround. If anyone else comes across the same problem, please comment/reopen this issue.
