### ISSUE TITLE
can't cancel fund setup or go to the previous step 

### ISSUE THREAD

**Issue by MouyouMoos** [avantgardefinance/melon-terminal#599]
It says:
"You have to complete the fund setup process for this fund before you can use it."

but I want to cancel the setup or if possible go to the first step "Begin Setup" but it's not possible.

**Comment by iherger** [comment]
Once you have started with the fund setup process, you cannot cancel it.

You can abandon the process, if you want to, and start setting up a fund with using a different manager address (each manager wallet can only have one fund).

**Comment by MouyouMoos** [comment]
How can I abandon this process ?

**Comment by fubhy** [comment]
Abandoning it means simply not continuing it. There is no way to "revert" it or go back to a previous step. If you want to start over with different configuration you have to do that using a different address.
