### ISSUE TITLE
Error in transaction "Begin setup"

### ISSUE THREAD

**Issue by ljuliandicarlo** [avantgardefinance/melon-terminal#602]
keep getting "transaction failed"

**Comment by iherger** [comment]
Sorry for the late reply. Was this resolved?

**Comment by adrien-supizet** [comment]
I encountered the same error when trying to create a fund. 

FYI I chose low gas fees (6gwei) vs medium (51) and fast (75)

**Comment by iherger** [comment]
Low gas fees can be problematic. If you really chose 6 gwei, then there is only a very small chance that this transaction will ever be mined (with the current gas conditions).

If you are using MetaMask, you can cancel your transaction or speed it up, see: https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction

**Comment by adrien-supizet** [comment]
> Low gas fees can be problematic. If you really chose 6 gwei, then there is only a very small chance that this transaction will ever be mined (with the current gas conditions).

I agree. I'm not sure it is related though as the transaction fails **instantly**, giving an error message in the Melon UI and a failed transaction in Metamask. The transaction was never submitted, I don't have the chance to speed it up.

**Comment by iherger** [comment]
Thanks for the background. 

Do you still get the error, or has it disappeared? If it's still there, then it would be great if you can help us debug it. You can DM me (you should be able to find me in the Melon Telegram channel or the Melon Discord).

**Comment by adrien-supizet** [comment]
It seems to be resolved now 😉 That's ashamed the fees are back to crazy expensive 😅 
Thank you!

**Comment by iherger** [comment]
Good to hear! Closing this for now, fee free to reopen if the problem occurs again.
