### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by sxj3388** [avantgardefinance/melon-terminal#603]
Investment amount too low,please return my WETH.use in metamask

**Comment by sxj3388** [comment]
HASH:0x5d3faddc6ec08a65afc06a90888b5719de756f85328f4f0e3a2e6e29411edaf9

**Comment by iherger** [comment]
You can cancel your investment request 24 hours after you sent it. You should be able to do this from the wallet page in the Melon Terminal, https://melon.avantgarde.finance/wallet (scroll down to "Pending investment requests")
