### ISSUE TITLE
Error in transaction "Create Accounting Contract"

### ISSUE THREAD

**Issue by 5awaja** [avantgardefinance/melon-terminal#607]

**Comment by iherger** [comment]
Were you able to create the contract after a while?

**Comment by 5awaja** [comment]
Yes, but it cost over a 1000 USD

**Comment by iherger** [comment]
Unfortunately, with the current high gas costs, fund creation is quite expensive (but still much cheaper than setting up a hedge fund in traditional finance). 

We are aware of the problem and we are working on reducing gas usage substantially for the next release.
