### ISSUE TITLE
Error in transaction "Create Policy Manager Contract"

### ISSUE THREAD

**Issue by xirkle** [avantgardefinance/melon-terminal#610]
Hi,

I'm going through the Create Policy Manager Contract process, and after some time, it timed out. 
For gas, it's set to average gas price, and I currently have over 2 ETH during this step.

Message: The transaction has failed. This is an error.

When I tried to run it again, I got this other message: Validation error: Undefined JSON-RPC result

**Comment by iherger** [comment]
Were you able to successfully deploy the contract?

**Comment by xirkle** [comment]
Yes I completed it.

**Comment by iherger** [comment]
Perfect!
