### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by xirkle** [avantgardefinance/melon-terminal#611]
I'm at step #9 and I got this error message after the contract's completion.

Oops, something went wrong!
Please reload the page in your browser (Ctrl/Cmd R) and try again.
If the error does not disappear after reloading, please file an error report.

C@https://melon.avantgarde.finance/static/js/12.fae83a40.chunk.js:1:12499
Ki@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2706844
No@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2715748
ys@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2754486
uc@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2745785
sc@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2745708
Xs@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2742717
qa/<@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2694102
t.unstable_runWithPriority@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2769684
Ha@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2693811
qa@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2694049
Ga@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2693982
Ys@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2739499
bo@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:2711219
Q/<@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1288134
J/<@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1288250
X/</e<@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1288836
_</t.onStateUpdate@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1274592
P</t.dispatch/<@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1277498
P</t.dispatch@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1277468
P</t.setData@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1279159
P</t.fetch/t.promise</</<@https://melon.avantgarde.finance/static/js/8.98ac616d.chunk.js:2:1282916

**Comment by iherger** [comment]
It's difficult to say what caused this error. I suspect this to be a connection error to our subgraph.

Closing this, feel free to reopen if the error happens again.
