### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by xirkle** [avantgardefinance/melon-terminal#612]
I successfully completed a transaction, and then, Melon asked me to do another transaction.

**Comment by iherger** [comment]
Investment into a fund requires two transactions: first you request an investment, and second you execute the request. Typically, you have to wait for an update of the price source between the first and the second step.

Was that error resolved in the end or are you still getting it?

**Comment by xirkle** [comment]
It took some effort and multiple attempts but I was able to complete it.
Thanks for checking in.

**Comment by iherger** [comment]
OK, that's good to hear.
