### ISSUE TITLE
Prove that I am a fund manager

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/melon-terminal#62]
We want for users to be able to prove that they are a Melon fund manager (this will be used to add them to a telegram chat which is exclusively reserved for Melon fund managers). 

To that end, we would like for a user to be able to sign with their private key a predefined message (for ex: "I am the manager of the Melon fund XXX"), and generate an email containing their public address, signed message, original message and telegram username. This email would be sent to an address such as meb@avantgarde.finance (MEB for Melon Exposed Businesses) and that would allow us to verify the signature before adding the user to the telegram channel (https://etherscan.io/verifySig). 

This could be a button in the configuration/settings section, only visible for fund managers.

**Comment by fubhy** [comment]
Can this be post release like we discussed yesterday?

**Comment by jennazenk** [comment]
Yes that one can be tackled post released @ishak-lm

**Comment by iherger** [comment]
This has been implemented a while ago.
