### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by ikaloooby** [avantgardefinance/melon-terminal#624]
Error - "Investment amount too low for the requested number of shares" in https://sarson-funds.melon.fund 
Meanwhile the payment in Weth from the wallet is missing.

**Comment by iherger** [comment]
This can happen when a fund's share price increases a lot between the time you send the investment request and the price update.

Yoru WETH are safe, they are in the Participation contract of the fund. You can call `cancelRequest()` in the wallet section of the Melon Terminal if the investment request is 24 hours ago or longer. If you don't call it, it will automatically be cancelled at the next price update.

**Comment by ikaloooby** [comment]
Ok. Got ir. Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 31, 2020 at 12:52 PM, Ivan Herger<notifications@github.com> wrote:   


Closed #624.
