### ISSUE TITLE
Error in transaction "Create Participation Contract"

### ISSUE THREAD

**Issue by gtscrypto** [avantgardefinance/melon-terminal#627]
"gas required exceeds allowance (12457276) or always failing transaction"

Gas prices are extremely high and this probably explains this error. Is that all there is to it? I am also wondering if more coins will be added to the selection approved for trading. Thanks.

**Comment by iherger** [comment]
Apologies for the late reply.

Yes, this was likely due to high gas prices.

More assets will be added with upcoming version 2 release (and afterwards).
