### ISSUE TITLE
General error "TypeError"

### ISSUE THREAD

**Issue by CyberKingDavid** [avantgardefinance/melon-terminal#630]
Hi Guys!

I completed the last step of fund setup yesterday, but something is not working properly. Can somebody help me?

Regards,
CKD

**Comment by erin-koen** [comment]
hi @CyberKingDavid - can you shoot me a message on telegram @eek637? I'll help you chase this down.

**Comment by CyberKingDavid** [comment]
> hi @CyberKingDavid - can you shoot me a message on telegram @eek637? I'll help you chase this down.

Thanks for the quick help!

**Comment by iherger** [comment]
This should be fixed now.
