### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by benadam17** [avantgardefinance/melon-terminal#632]
Hi there,
I would like to invest a fund, but appear this message in Execution window; Error in transaction

Can yo help to me?

Regards,
B17

**Comment by iherger** [comment]
Currently, gas prices are really high, and you might not have enough ETH in your wallet to pay for the transaction.

Can you give us the fund, and your wallet address?

**Comment by benadam17** [comment]
Hello,

Thank you your answer.

Of course,
wa: 0x78f3414028578F2D1a76041a4BdD54Be3341148b
fund: Cryptopope Fund

**Comment by iherger** [comment]
Thanks. 

Indeed, you don't have enough ETH in your wallet. To be safe, you should have 0.1 ETH or more.

**Comment by benadam17** [comment]
Thanks!
