### ISSUE TITLE
Error in transaction "Execute investment request"

### ISSUE THREAD

**Issue by webpolis** [avantgardefinance/melon-terminal#636]
Hi

I'm trying to execute my investment in https://melon.avantgarde.finance/mainnet/fund/0xf31ae95ffc10e73677461ee522840d9cd1ab8e84/invest but I get:

**Investment amount too low for the requested number of shares.**

My pending investment:

```
Fund name | Request date | Request asset | Request amount | Requested shares | Status
-- | -- | -- | -- | -- | --
Ultraverse Capital | 2020/09/23 15:40 GMT-3 | ZRX | 184.8788 | 0.0318 | Execute investment request
```
I cannot either add more ZRX because the INVEST button isn't responding so my funds are trapped. Please advise.

![image](https://user-images.githubusercontent.com/1072797/94172676-2d1b3380-fe69-11ea-867c-cb0522f14168.png)

**Comment by perhamgirl** [comment]
hey there, your investment request will automatically be released after 24hours and then you can re-submit it if you like with a different limit.

**Comment by webpolis** [comment]
Awesome, thanks.

**Comment by webpolis** [comment]
@perhamgirl now I only get the option to CANCEL. Any way I can just add more funds instead and avoid cancellation fee?
