### ISSUE TITLE
wrong timeline for Monthly returns chart

### ISSUE THREAD

**Issue by srust99** [avantgardefinance/melon-terminal#656]
i only set up the fund in October however the performance monthly returns are marked down in february and march

<img width="861" alt="Screenshot 2020-12-02 at 2 49 44 PM" src="https://user-images.githubusercontent.com/1955258/100838609-b6746500-34ad-11eb-8c55-a75597aa25ae.png">

**Comment by iherger** [comment]
Thanks for reporting, this has just been fixed.
